### ISSUE TITLE
i18n string "label_disabled" conflicts with the one in Redmine core

### ISSUE THREAD

**Issue by vividtone** [agileware-jp/redmine_issue_templates#1]
## Summary

The plugin unintentionally redefines the i18n string "label_disabled" which is already defined in Redmine.

https://www.redmine.org/projects/redmine/repository/entry/branches/4.1-stable/config/locales/en.yml#L864
https://github.com/agileware-jp/redmine_issue_templates/blob/master/config/locales/en.yml#L7

As a result, a test fails.

```
$ ruby test/functional/users_controller_test.rb
Run options: --seed 57427

# Running:

............................................F

Failure:
UsersControllerTest#test_index_csv [test/functional/users_controller_test.rb:86]:
"disabled" not found in "dlopper,Dave,Lopper,dlopper@somenet.foo,No,active,Disable,07/20/2006 02:33 AM,07/20/2006 02:33 AM,"","","","""


bin/rails test test/functional/users_controller_test.rb:69
```

I think the key name "label_disabled" should be changed.

**Comment by ishikawa999** [comment]
It looks like label_disabled is not used in this repository at the moment.
label_disabled was added in the first commit of this repository and has since been obsolete due to a change in https://github.com/agileware-jp/redmine_issue_templates/commit/0fa54597ea0da76af162259773e6c33e701fd5c0#diff-e5599691f373b10ced28bfecf6b66e055eb237f25f614fcd7047d81b8a77d1c2L63.

I think it's okay to remove label_disabled from config/locales/*.yml.

**Comment by ishikawa999** [comment]
Test UsersControllerTest#test_index_csv that fails has been added since Redmine 4.2.

**Comment by ishikawa999** [comment]
This issue should have been resolved because https://github.com/agileware-jp/redmine_issue_templates/pull/9  was merged.
Close.
